const PHONE='918050763648';
const imgs=['assets/services/sump-waterproofing.png','assets/services/terrace-waterproofing.png','assets/services/bathroom-epoxy-grouting.png','assets/services/brush-bonding-services.png','assets/services/floor-coating.png'];
const services=[['sump-waterproofing','Sump Waterproofing','Long-lasting waterproofing that prevents leaks and water contamination.','We apply premium cementitious and polymer-based systems to sumps, sealing cracks and porous surfaces for long-term protection.',['Stops leaks & seepage','Prevents contamination','10+ years lifespan','Non-toxic, potable-water safe'],['Surface preparation','Crack sealing & priming','Multi-coat membrane','Curing & water test']],['terrace-waterproofing','Terrace Waterproofing','Protect your terrace from rainwater leaks and weather damage.','Complete terrace waterproofing using elastomeric membranes and PU coatings, tailored to your terrace condition.',['Zero monsoon leaks','Heat reflective finish','Protects RCC & rebar','Warranty-backed application'],['Terrace inspection','Surface preparation & crack repair','Primer + waterproof coating','Ponding test & handover']],['bathroom-epoxy-grouting','Bathroom Epoxy Grouting','Premium grout for a hygienic, waterproof bathroom finish.','Replace crumbling cement grout with premium epoxy grouting for a mould-resistant, showroom-fresh bathroom finish.',['100% waterproof joints','Stain & mould resistant','Designer colour range','Easy-care surface'],['Old grout removal','Deep joint preparation','Epoxy grout application','Buffing & finishing']],['brush-bonding-services','Brush Bonding Services','A durable protective coating for concrete surfaces.','Two-component epoxy polymer modified cementitious brush-bond coating for wet areas, water tanks and terraces.',['Excellent bonding on concrete','Flexible crack bridging film','Non-toxic & odourless','Ideal for wet areas'],['Substrate preparation','Mixing brush bond slurry','2–3 coat brush application','Curing & inspection']],['floor-coating','Floor Coating','Tough, seamless floor protection with a clean finish.','Durable floor coating systems for homes, parking areas and commercial spaces that resist stains, moisture and daily wear.',['Dust-free, easy-care surface','Stain and chemical resistant','Improves floor durability','Professional smooth finish'],['Floor assessment','Surface grinding & repair','Primer application','Protective top coat']]].map((s,i)=>({id:s[0],name:s[1],image:imgs[i],short:s[2],desc:s[3],benefits:s[4],process:s[5]}));
const wa=m=>`https://wa.me/${PHONE}?text=${encodeURIComponent(m)}`;
const image=(s,c='')=>`<div class="photo photo-image ${c}" style="background-image:url('${s.image}')">${s.name}</div>`;
const card=s=>`<article>${image(s)}<h3>${s.name}</h3><p>${s.short}</p><a class="learn" href="index.html#${s.id}">Learn More →</a></article>`;
const row=s=>`<section class="service-row" id="${s.id}">${image(s,'service-image')}<div class="service-copy"><p class="eyebrow blue">SERVICE</p><h2>${s.name}</h2><p>${s.desc}</p><div class="service-details"><div><h3>BENEFITS</h3><ul>${s.benefits.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="process"><h3>OUR PROCESS</h3><ul>${s.process.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><div class="button-row"><a class="btn btn-green" href="${wa(`Hello Unnati Services, I'm interested in ${s.name}. Please share details and a quote.`)}" target="_blank">◉ WhatsApp</a><a class="btn btn-outline" href="tel:+918050763648">⌕ Call Now</a></div></div></section>`;
document.querySelectorAll('[data-wa]').forEach(a=>{a.href=wa(a.dataset.wa);a.target='_blank'});const cards=document.querySelector('#home-service-cards');if(cards)cards.innerHTML=services.slice(0,3).map(card).join('');const list=document.querySelector('#service-list');if(list)list.innerHTML=services.map(row).join('');

const footer=document.querySelector('#footer');if(footer)footer.innerHTML=`<div class="footer-grid"><div class="footer-about"><a class="brand" href="index.html"><span class="brand-mark">✦</span><span><b>Unnati Service</b><small>WATERPROOFING · PROTECTION</small></span></a><p>Professional waterproofing and protective coating services delivered with care, quality and complete reliability.</p></div><div><h3>QUICK LINKS</h3><a href="index.html">Home</a><a href="services.html">Services</a><a href="contact.html">Contact</a></div><div><h3>SERVICES</h3>${services.map(s=>`<a href="index.html#${s.id}">${s.name}</a>`).join('')}</div><div><h3>CONTACT</h3><a href="tel:+918050763648">⌕ +91 80507 63648</a><a href="mailto:slvgreenleafreatil@gmail.com">✉ slvgreenleafreatil@gmail.com</a><a target="_blank" href="https://maps.app.goo.gl/XsKxjttScJd79ALj8">⌖ Bengaluru, Karnataka, India</a><a>◉ Mon – Sun: 9:00 AM – 8:00 PM</a></div></div><div class="footer-copy"><span>© 2026 Unnati Service. All rights reserved.</span><span>Crafted with care for protected spaces.</span></div>`;
document.querySelector('.menu-toggle')?.addEventListener('click',()=>document.querySelector('.main-nav').classList.toggle('open'));document.querySelector('.enquiry-form')?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);window.open(wa(`Hello Unnati Services, I would like an enquiry.\n\nName: ${d.get('name')}\nPhone: ${d.get('phone')}\nService: ${d.get('service')}\nMessage: ${d.get('message')}`),'_blank')});
